const TIP_TYPES = {
  AE_TIP: 'AE_TIP',
  TOKEN_TIP: 'TOKEN_TIP',
  DIRECT_AE_TIP: 'DIRECT_AE_TIP',
  DIRECT_TOKEN_TIP: 'DIRECT_TOKEN_TIP',
  POST_WITHOUT_TIP: 'POST_WITHOUT_TIP',
};

module.exports = {
  TIP_TYPES,
};
