version: "3.6"
services:
  superhero-backend:
    image: aeternity/superhero-backend
    container_name: superhero-backend
    ports:
      - "3000:3000"
    cap_add:
      - SYS_ADMIN # required for the browser / link preview crawler
    depends_on:
      - redis
      - postgres
      - ipfs
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_URL=https://mainnet.aeternity.io
      - COMPILER_URL=https://latest.compiler.aepps.com
      - CONTRACT_V1_ADDRESS=ct_2AfnEfCSZCTEkxL5Yoi4Yfq6fF7YapHRaFKDJK3THMXMBspp5z
      - CONTRACT_V3_ADDRESS=ct_2Hyt9ZxzXra5NAzhePkRsDPDWppoatVD7CtHnUoHVbuehwR8Nb
      - TOKEN_REGISTRY_ADDRESS=ct_2n76BQCN3zNEjuEvHFNZtgyWPc5zizy47wNrUT3RHP2MrPKhbq
      - ORACLE_CONTRACT_ADDRESS=ct_7wqP18AHzyoqymwGaqQp8G2UpzBCggYiq7CZdJiB71VUsLpR4
      - MIDDLEWARE_URL=https://mainnet.aeternity.io/mdw
      - IPFS_URL=http://ipfs:5001
      - PUBLIC_KEY=ak_yrVCHP97UWfCRGMCaojBjdSKuXD3yyC8NkzkReURd4t3jbCQW # use an account with some tokens here
      - PRIVATE_KEY=f38eecf78a521fcbf34d253b6681f69e0f64d99526d63e18f205e03cf30dd1248117982ba9504170f1f40c66c137c1823244dc7795950a85807793626e69ebce
      - AUTHENTICATION_USER=user # used for blacklisting & flagging ui, replace with your own credentials
      - AUTHENTICATION_PASSWORD=password # used for blacklisting & flagging ui, replace with your own credentials
      - NODE_ENV=production
      - WEBSOCKET_URL=wss://mainnet.aeternity.io/mdw/websocket
      - ORACLE_GETTER_ADDRESS=ct_anbp2U5VUsF6PkrX1ER1hSqj76Krpvqy97c5JBLmubBecCWui
      - CONTRACT_V1_GETTER_ADDRESS=ct_NR7Bd7j5LRdzvKZmrMagMkfxzG8ZPWseKQkdwWootpq4kAJY2
      - CONTRACT_V3_GETTER_ADDRESS=ct_2NdZ6PX9tZHWFhgcoYjthYNFF15qxjDwFSsNXRPeajEWazxkTo
      # all optional
      - POSTGRES_PASSWORD=postgres # replace with your own credentials
      - POSTGRES_USER=postgres # replace with your own credentials
      - POSTGRES_DB=superhero
      - POSTGRES_HOST=postgres
    restart: always

  redis:
    image: redis
    hostname: redis
    restart: unless-stopped
    container_name: superhero-redis

  postgres:
    image: postgres:12
    hostname: postgres
    restart: unless-stopped
    container_name: superhero-postgres
    environment:
      - POSTGRES_PASSWORD=postgres # replace with your own credentials
      - POSTGRES_USER=postgres # replace with your own credentials
      - POSTGRES_DB=superhero

  ipfs: # this instance will sync with other peers and act as a p2p node, check the ipfs config to avoid that
    image: ipfs/go-ipfs
    hostname: ipfs
    restart: unless-stopped
    container_name: superhero-ipfs
