const NOTIFICATION_TYPES = {
  COMMENT_ON_COMMENT: 'COMMENT_ON_COMMENT', // ENTITY, RECEIVER AND NOTIFICATION_TYPE ARE ENOUGH
  COMMENT_ON_TIP: 'COMMENT_ON_TIP', // ENTITY, RECEIVER AND NOTIFICATION_TYPE ARE ENOUGH
  TIP_ON_COMMENT: 'TIP_ON_COMMENT', // ENTITY, RECEIVER AND NOTIFICATION_TYPE ARE ENOUGH
  RETIP_ON_TIP: 'RETIP_ON_TIP', // TIPID + RETIP ID + NOTIFICATION_TYPE ARE ENOUGH
  CLAIM_OF_TIP: 'CLAIM_OF_TIP', // ENTITY AND NOTIFICATION_TYPE ARE ENOUGH
  CLAIM_OF_RETIP: 'CLAIM_OF_RETIP', // TIPID + RETIP ID + NOTIFICATION_TYPE ARE ENOUGH
};

const NOTIFICATION_STATES = {
  CREATED: 'CREATED',
  READ: 'READ',
};

const ENTITY_TYPES = {
  COMMENT: 'COMMENT',
  TIP: 'TIP',
};

const SOURCE_TYPES = {
  COMMENT: 'COMMENT',
  TIP: 'TIP',
  RETIP: 'RETIP',
};

module.exports = {
  NOTIFICATION_TYPES,
  NOTIFICATION_STATES,
  ENTITY_TYPES,
  SOURCE_TYPES,
};
