const NOTIFICATION_TYPES = {
  COMMENT_ON_COMMENT: 'COMMENT_ON_COMMENT',
  COMMENT_ON_TIP: 'COMMENT_ON_TIP',
  TIP_ON_COMMENT: 'TIP_ON_COMMENT',
  RETIP_ON_TIP: 'RETIP_ON_TIP',
};

const NOTIFICATION_STATES = {
  CREATED: 'CREATED',
  READ: 'READ',
};

const ENTITY_TYPES = {
  COMMENT: 'COMMENT',
  TIP: 'TIP',
};

module.exports = {
  NOTIFICATION_TYPES,
  NOTIFICATION_STATES,
  ENTITY_TYPES,
};
