const fs = require('fs');

const { sequelize } = require('../models');

const { models } = sequelize;
const result = Object.keys(models).map(model => {
  const attributes = models[model].attributes || models[model].rawAttributes;
  return {
    model,
    fields: Object.keys(attributes).map(column => ({
      column,
      type: attributes[column].type.constructor.key,
      // eslint-disable-next-line no-underscore-dangle
      allowNull: attributes[column].allowNull || attributes[column]._autoGenerated,
      values: attributes[column].values,
    })),
  };
});

const typeMapping = type => {
  switch (type) {
    case 'enum':
    case 'date':
    case 'text':
    case 'uuid':
      return 'string';
    default:
      return type;
  }
};

const formatMapping = type => {
  switch (type) {
    case 'date':
      return 'date-time';
    case 'text':
      return 'text';
    case 'uuid':
      return 'uuid';
    default:
      return undefined;
  }
};

const openAPIJSON = {
  components: {
    schemas: result.reduce((acc, model) => ({
      ...acc,
      [model.model]: {
        type: 'object',
        required: model.fields.filter(field => !field.allowNull).map(field => field.column),
        properties: model.fields.reduce((allProperties, curr) => ({
          ...allProperties,
          [curr.column]: {
            type: typeMapping(curr.type.toLowerCase()),
            format: formatMapping(curr.type.toLowerCase()),
            ...(curr.type === 'ENUM') && { enum: curr.values },
          },
        }), {}),
      },
    }), {}),
  },
};

const swagger = JSON.parse(fs.readFileSync('./swagger.json'));
const merged = {
  ...swagger,
  components: {
    ...swagger.components,
    schemas: {
      ...swagger.components.schemas,
      ...openAPIJSON.components.schemas,
    },
  },
};
fs.writeFileSync('./swagger.json', JSON.stringify(merged));
