const TRACE_STATES = {
  REQUEST_RECEIVED: 'REQUEST_RECEIVED',
  BODY_RECEIVED: 'BODY_RECEIVED',
  DATA_PARSED: 'DATA_PARSED',
  CLAIM_AMOUNT: 'CLAIM_AMOUNT',
  INITIAL_PRECLAIM_RESULT: 'INITIAL_PRECLAIM_RESULT',
  ESTIMATED_FEE: 'ESTIMATED_FEE',
  PRECLAIM_STARTED: 'PRECLAIM_STARTED',
  STARTED_PRE_CLAIM: 'STARTED_PRE_CLAIM',
  CAUGHT_ERROR: 'CAUGHT_ERROR',
  REQUEST_ANSWERED: 'REQUEST_ANSWERED',
  FINAL_PRECLAIM_RESULT: 'FINAL_PRECLAIM_RESULT',
  CLAIM_RESULT: 'CLAIM_RESULT',
  ERROR: 'ERROR',
  FINISHED: 'FINISHED',
};
export { TRACE_STATES };
export default {
  TRACE_STATES,
};
