# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: rm -rf package-lock.json
    - run: npm i
    - run: docker run --name server-redis -p 6379:6379 -d redis
    - run: docker run --name ipfs_host -p 5001:5001 -d ipfs/go-ipfs
    - run: npx sequelize-cli db:migrate
    - run: npm test
      env:
        REDIS_URL: redis://localhost:6379
        IPFS_URL: http://localhost:5001
